### ISSUE TITLE
Space includedIn Outgoing relationship removed

### ISSUE THREAD

**Issue by cbupp** [RealEstateCore/rec#148]
With REC4, the 2-way relationship between a Space and a collection was removed. A Portfolio can still `include` a space, but the space's `includeIn` relationship was removed.

Was this intentional, or can I submit a PR?

**Comment by hammar** [comment]
Hi,

Good question! This is somewhat intentional, but it is not set in stone. 

The rationale is as follows:

1. For all of those relationships with unset targets, (i.e., `Class.Relationship -> ANY`), if we consistently wanted their inverses available throughout the ontology, we would have to set up such inverse relationships for every defined type (so not only `Space.includedIn` but also `Asset.includedIn`, `Agent.inludedIn`, `Point.includedIn`, etc etc. This would increase maintenance for little perceived gain (since querying can be done in either direction, so one might as well write queries in the other direction).
2. In the RDF/SHACL world it is possible, and indeed common, to declare relationships as being each other's inverses, which will at query time (provided a suitable reasoner is plugged into the query engine) resolve queries in either direction based on the assertion of such a relationship in only one direction. If we were to provide relationships going in both directions, we would probably confuse users of our SHACL models (if we do not include such inverse declarations there), or we would create a situation where the DTDL and SHACL models diverge (if we do include them in SHACL -- since DTDL does not have such inverse support).

If our assumptions on this are faulty, we'd love to take a discussion and possibly adjust this. That's what the public preview is all about! 

Best,

Karl

**Comment by cbupp** [comment]
Thanks for the response Karl.

I had assumed that there was a potential performance gain in Azure Digital Twin by implementing the 2 way relationships. But after some (very basic) test queries, the timing and query cost appear identical. Good to know!
