### ISSUE TITLE
levelNumber for mezzanines?

### ISSUE THREAD

**Issue by jbkoh** [RealEstateCore/rec#153]
Hi there,

I was trying to model mezzanines with REC, and found that [MezzanineLevel](https://github.com/RealEstateCore/rec/blob/89489a4133f51a5ac5bb207f2d78d43f2387e863/Doc/Space/Architecture/Level/MezzanineLevel.md) inherits the property `levelNumber` from `Level`, which is integer. What's the intended behaviors for the property? E.g., there is a mezzanine on the 3rd floor. What's the `levelNumber` of the mezzanine? Assuming the 3rd floor's levelNumber is 2, is 3 the right levelNumber for the mezzanine? And should the 4th floor have the levelNumber as 4? 

And what if there are multiple mezzanines with different heights on the same floor? Should they share the same levelNumber or different ones?

Thanks!

**Comment by hammar** [comment]
Hi,

We are not prescriptive on this; practices on level numbering differ from country to country and company to company, so it is hard to set a one-size-fits-all rule for how to represent this (sometimes this even varies within a building itself, if it is large enough and remodelled/expanded over time). There's a reference to this choice in the previous version of this interface at https://github.com/Azure/opendigitaltwins-building/blob/master/Ontology/Space/Level/Level.json, we should probably update the REC4 level description to read similarly.

If the integer schema is overly strict, one option might be to move to a floating point schema allowing for level numbers like "2.5". @erikoskarwallin do you have feedback on this -- would it break assumptions/implementations in any major ways?

Karl

**Comment by jbkoh** [comment]
Regardless of how heterogeneous it is used in the real world, a standard should standardize it if we expect users need that info in buildings.

The problem with floating point is that floating points are not uniformly implemented across different systems, so the exact comparison is not working as we expect. It's generally known to discourage exact comparison of floating points. So if we go to the path of assigning levelNumbers to mezzanines, it should be [decimal](https://en.wikipedia.org/wiki/Decimal_data_type).

However, I argue we shouldn't use levelNumbers for mezzanines but rather consider those as a type of space in the floor.
- Once numbers are assigned, it should mean something numerically.
  - Why 2.5 instead of 2.3 or 2.7?
  - What if there are multiple mezzanines within the floor with different heights?
- It may vary by region but [A mezzanine does not count as one of the floors in a building, and generally does not count in determining maximum floorspace.](https://en.wikipedia.org/wiki/Mezzanine#Definition)

So I'd propose those:
- MezzanineLevel is not a type of Level. 
- Just call it Mezzanine
- Drop levelNumber for Mezzanine
- Maybe add a property called `height` to indicate how high the Mezzanine is from the corresponding Level.

**Comment by hammar** [comment]
I'm not sure I agree on your first assessment -- if there is great variability in real world usage/definitions, it is in my view better to be descriptive and allow for such variability in modelling, than to be prescriptive and block usage of the model. See for instance how we are not prescriptive in terms of spatial topology: building -> wing -> level is just as valid as building -> level -> wing, because this varies among our users. But there is of course always a discussion and a tradeoff, and we would generally want to avoid providing users with _unnecessary_ "footguns" in the form of ambiguous modelling choices, when not needed. 

Agree on float, decimal is better -- poor use of words on my part (though to be honest, I'd think that at the precision we'd be dealing with float comparison issues should not come into play)

All of that being said, your solution of Mezzanine just being a space does sound elegant to me. Maybe mezzanines are not levels in this sense. I'll put this on the next REC TC meeting agenda for discussion. Until then, pinging some folks who might use MezzanineLevel as currently defined and who should probably read this thread and consider impact of such a potential change in their systems: @erikoskarwallin @PeteHart @perkarlberg @rszcodronski

**Comment by jbkoh** [comment]
Thanks for the directions and happy to have more inputs on the Mezzanines. Would love to keep hearing the updates on this issue.

On the topic of the scope of the standard: it's a typical tradeoff that a piece of information should be normalized at either the modeler side or the interpreter side. If REC allows building->wing->floor and building->floor->wing at the modeler side (the ontology), an interpreter (e.g., an app) should consider both of the cases whenever it needs related information from the source. Especially, this is a case where the actual buildings are not different but just about how people call those, for which a standard can make a voice. I understand your position that REC wants more flexibility, because we have a similar position at Brick, but that burdens the app side, imho.

**Comment by rszcodronski** [comment]
Mezzanine may be vague which is why Mezzanine Level was used for this scenario. It is intended to be used for Buildings which do have a well-defined Mezzanine Level which is a specific type of Level that doesn't span the extent of the building footprint. These are commonly indicated in a building stacking plan and in a list of elevator stops.

I think it's pretty well-defined that it's intended to be "ordinal" such that if there is a 3rd floor mezzanine and the 3rd floor is levelNumber: 2, 3M would be levelNumber: 3, and 4th floor would be levelNumber: 5.

Alternatively, I would be ok with "relaxing" the description of levelNumber to allow for its use to be decimal such that a consumer could do:
3rd floor levelNumber 2, 3M levelNumber 2.5, 4th floor levelnumber: 3.

**Comment by hammar** [comment]
Great feedback, thanks @rszcodronski, @jbkoh!

Another suggestion for consideration/discussion:

1. We keep Mezzanine as MezzanineLevel (and consequently w/ an integer levelNumber)
2. We redefine the textual description of levelNumber to clarify that it is used for ordering _within the containing space_ rather than within the building as a whole

This solution would allow one to model mezzanines as normal levels when it is appropriate, in which case levelNumber refers to "absolute" ordering within the containing building; or it allows to model them as contained _within_ levels, when that is more appropriate. In the latter case, the mezzanine level numbers would indicate ordering within that level.

PS: Agree fully on the tradeoff @jbkoh -- which is why I think _unnecessary_ ambiguity/flexibility is bad. The question is whether this is unnecessary. I'm leaning towards no.

**Comment by jbkoh** [comment]
Hi Karl, thanks for discussing this and preparing a PR. Could you clarify this one?
> In either case, levelNumber indicates the ordering within the containing space.
Do you mean the levelNumber is an ordering within the parts of the parent? E.g., if a mezzanine is a part of level 4, is the mezzanine's levelNumber 1?

**Comment by hammar** [comment]
> > In either case, levelNumber indicates the ordering within the containing space.
> 
> Do you mean the levelNumber is an ordering within the parts of the parent? E.g., if a mezzanine is a part of level 4, is the mezzanine's levelNumber 1?

Yes, that is the intended design here. If there are multiple mezzanines modelled as constituent elements within one containing Level, they can be ordered with respect to one another using the levelNumber field. The first would be 1, the second would be 2, etc. Or if one prefers zero-indexing, 0, 1, etc. That parent Level will in turn use its levelNumber for ordering with respect to its sibling levels in the parent building or sub-building. 

IF one instead chooses to model the mezzanine as a first-order level (which some cultures/contexts can elect to do), then the parent element will be the building/sub-building directly, and levelNumber will indicate ordering within it.
