### ISSUE TITLE
hasPoint missing for Blind_Group

### ISSUE THREAD

**Issue by adalbertogc1** [RealEstateCore/rec#211]
In [DTDLv2](https://github.com/RealEstateCore/rec/tree/main/Source/DTDLv2), a [Point ](https://dev.realestatecore.io/ontology/Point/Point) can have `isPointOf` relationship to a [Blind_Group](https://dev.realestatecore.io/ontology/Collection/System/Shading_System/Blind_Group), however a  `Blind_Group `cannot have a  `hasPoint` relationship to any `Point`. 

I am building  a model in Azure Digital Twins where I need outgoing relationships from `Blind_Group` to its corresponding points, see relationships in red in the image below. I can make a custom extension of  `Blind_Group`  but I am reporting it in case it needs to be fixed.

<img width="441" alt="image" src="https://user-images.githubusercontent.com/46672847/205933752-becd89e8-4240-40fa-871d-2c23cd2cef9d.png">

**Comment by hammar** [comment]
Hi,

This has been by design; see the illustration at https://github.com/RealEstateCore/rec, copied below:

![image](https://user-images.githubusercontent.com/68027/207055191-dcf89997-d248-4942-91ae-aef5ba346f6b.png)

The idea is that physical/tangible things (e.g., Architecture spaces, Assets) can have points, while collections, being intended as administrative groupings of such physical/tangible things, do not have any points on their own. This is in line with the design of Brick Schema, our upstream source of Point and Equipment definitions.

`isPointOf` does not have a DTDL `target` declaration set because DTDL does not allow union expressions in targets; otherwise, if the language allowed it, that target would be something like `Union(Architecture,Asset). 

There has been some requests on getting a `hasPoint` property on collections as well (it's a seemingly useful abstraction and also needed for, e.g. water heating loops), so I'll try to see if I can get our colleagues in Brick on board with the idea.

**Comment by adalbertogc1** [comment]
Thank you for your comprehensive explantion Karl. I agree that, in principle, collections cannot have any points on their own. But I think that the hot water loop example you mentioned and the blind group are strong examples of collections that have points.
For example, the description of `blind group` is "A group of Blinds commonly attached to a single controller", but in REC I am not aware of a way to represent the actual blind controller (for example [this one](https://downloads.jung.de/public/en/pdf/productdocumentation/en_230xx1SR_20210427_td.pdf)), hence, I am using the blind group for representing the controller that deals with the individual blinds, which will have a number of setpoints and sensors. 

If I am missing something, please let me know :)

**Comment by hammar** [comment]
I absolutely see this need, and we're working on porting over some types from REC 3.3 into this DTDL version, specifically the subclasses of https://doc.realestatecore.io/3.3/asset.html#ICTEquipment (which we hope to upstream into Brick at some point also, contingent on them wanting it). Once we get that in place, hopefully shortly (we've got TC membership working on it as we speak), then you might for instance use something like https://doc.realestatecore.io/3.3/asset.html#Controller to represent that controller unit.

**Comment by hammar** [comment]
Closed with the merger of #229 which provides the requested Controller interface: https://github.com/RealEstateCore/rec/blob/main/Source/DTDLv2/RealEstateCore/Asset/Equipment/ICTEquipment/Controller/Controller.json

We're still aware of the interest for connecting points to more things, and will keep an eye on this, in tandem with the friends at Brick
