### ISSUE TITLE
Not possible to extend the options in an enum-property?

### ISSUE THREAD

**Issue by mwdhont-auge** [RealEstateCore/rec#217]
Hi, 

When I try to create an extension of the enumValues of a Property of the type Enum, I get the message below:

"dtmi:org:auge:Point;1, because it transitively 'extends' dtmi:org:brickschema:schema:Brick:Point;1, has property 'contents' that contains more than one element whose property 'name' has value 'hasQuantity'. Either change the value of property 'name' to a unique string value, or remove one or more 'extends' properties so that 'contents' will not be imported."

What's the approach to extend the enumValues? 

Michiel

[6. Extend EnumValues of Enum.zip](https://github.com/RealEstateCore/rec/files/10218402/6.Extend.EnumValues.of.Enum.zip)

**Comment by hammar** [comment]
Unfortunately DTDL does not allow for the overloading of existing Content elements at this time, only the addition of new ones. So the only way of extending an enum is to do it upstream, in the parent Interface on which the enum is defined.

**Comment by mwdhont-auge** [comment]
Is this something that could be taken up for DTDLv3, because from my non-expert understanding, it is actually 'bad practice' to change the base model, right? 
It will break future compatibility, or at least it will require manual rework.

**Comment by hammar** [comment]
I can feed this back to the DTDL team. Similar issues have been raised w.r.t. e.g., changing semantic types between metric and imperial units, which is also a kind of field overloading. So from my point if view it certainly merits discussion.

**Comment by cbupp** [comment]
@mwdhont-auge - I'm not sure this is something that DTDL should enable. It breaks the [Liskov Substitution principle](https://en.wikipedia.org/wiki/Liskov_substitution_principle) (though, I'm not sure DTDL explicitly follows it...)

i.e. If a system doesn't understand what a `dtmi:org:auge:Point;1` but knows that it extends `dtmi:org:brickschema:schema:Brick:Point;1`, the system can just treat the twin as the base class. This becomes broken, because the system doesn't know what "External_Temperature" is... that requires business logic to know.

For your implementation, would it make more sense to use `customTags` or `customProperties`? 

Alternatively, if these are intended to represent Sensors inputs, you could create "Internal_Air_Temperature_Sensor" and "External_Air_Temperature_Sensor" extensions.

**Comment by mwdhont-auge** [comment]
Hi @cbupp,

I don't see what the difference is between adding a property to a class extension and extending the list of optional arguments of a propoperty. In both cases, the system won't understand the full interpretation if it has no knowledge about the 'dtmi:org:auge:Point;1'-model.

customTags or customProperties feel a bit like the trash bin for everything which is not suffiiciently covered by the native ontology. I would like to limit the use of it as much as possible. I would rather add a new property.


Could you elaborate your last suggestion, I don't see how this would work?

**Comment by hammar** [comment]
As this issue concerns the DTDL language rather than RealEstateCore, I'll be closing the issue, referring further discussion to the repo https://github.com/Azure/opendigitaltwins-dtdl.
