### ISSUE TITLE
CustomTags only saves boolean value in RECv4

### ISSUE THREAD

**Issue by heidimao** [RealEstateCore/rec#219]
We are trying to save some custom value for our twins with REC v4 DTDL schematics to Azure Digital Twin Service.
We have some custom values, such as `displayName`, `roomType`, `id`, we used to save them in customTags field with REC v3.
When migrating to v4, we notice that customTags only accepts boolean value, is there a way to save these custom value with v4?
Thanks

**Comment by hammar** [comment]
Absolutely -- that's what the new customProperties field is for. It is a nested map of `(string -> (string -> string))`, where the outer key can be used to represent a namespace, and the inner key-> value represent a property and value within that namespace. 

We had feedback from users asking for such a namespace feature, e.g., to group custom values by originating system or other source. If you prefer a single flat namespace, just use the same outer key for all your code, calling it something sensible ("default" perhaps?) or set it to an empty string (though beware: the latter makes for somewhat annoying JSON Patch documents when updating).

Since we now have that expressivity, it made sense to reduce customTags to a simple tagging schema instead, which is more consistent with how the term "tag" is typically used.

Hope this makes sense; if there's anything else I can answer, just ping here.

Best,

Karl

**Comment by Booli** [comment]
Hey Karl,

thanks for your respons. We were using customTags, and not customProperties. If I look at the [ontology documentation](https://dev.realestatecore.io/ontology/Asset/Asset]), I can't find any reference to the customProperties field, is it out of date?

**Comment by hammar** [comment]
Those docs are probably a little out of date. They are a mirror of the docs that are in the repo itself (https://github.com/RealEstateCore/rec/tree/main/Doc), that are copied over to the dev site every so often, while the ones in the repo are generated automatically on any merged PR to the mainline branch. I should probably sort that out on the CI end, so that they are likewise copied to the dev site every time, thanks for reminding me.

**Comment by hammar** [comment]
Those docs should now be up-to-date with what's in the repo, and hopefully they'll stay updated w/ any pushes to main. Closing the issue as I think we've resolved it, but if there's anything else in this thread you'd like to discuss further, do feel free to re-open it.
