### ISSUE TITLE
Option to Distinguish Delta's and Total Consumption

### ISSUE THREAD

**Issue by ogiel** [RealEstateCore/rec#247]
Hi all,

To be able to distinguish the energy consumption between a delta or a total we use the models Energy Usage Sensor and Energy Sensor respectively. However, we are also encountering differences between deltas and totals for other measurement types like water or gas.

Would it be an idea to do this general separation of models for more liquids and gases? Or are we viewing this in the wrong way completely?

EDIT:
I think we should actually be using the aggregate component that exists on all sensors for distinguishing these timespan types.

**Comment by steveraysteveray** [comment]
You might be interested to read how we treat this in the QUDT ontology [here](https://github.com/qudt/qudt-public-repo/wiki/Support-for-measures-of-absolute-values-and-for-intervals-(differences)). QUDT is used by Brick.

**Comment by ogiel** [comment]
Hey @steveraysteveray thanks for the response! The part: 

"To support this, the qudt:Quantity class has a property qudt:isDeltaQuantity. It is associated with the qudt:Quantity because the quantity describes the context of the measurment. qudt:isDeltaQuantity is a boolean property to record whether the measurement is an absolute value of the Quantity instance, or a delta (or difference) value. Setting isDeltaQuantity to "true" means the measurement is an interval. isDeltaQuantity set to "false" means the measurement is an absolute value. An application can then take the appropriate action, such as in unit conversion, etc." 

exactly describes a possible solution we are looking for, but I'm afraid this is not an option in REC. By using the aggregate component we can specify aggregationFunction with one of the options: `count`, `max`, `mean`, `median`, `min`, `mode` and `sum`. However, I would rather have these reserved for when we actually have a function on our side rather than specifying how external APIs do it on their side.

**Comment by steveraysteveray** [comment]
Of course, it's entirely your choice. I would argue that distinguishing a difference measurement from an absolute measurement is intrinsic to the measured quantity (rather than an external application), so we chose to keep that aspect associated directly with the quantity.

**Comment by hammar** [comment]
We have debated back and forth whether a REC-based graph should be time-indexed or not -- i.e., if deltas across multiple readings should be represented in the graph or whether that is in the domain of some other system. In our experience, most often one will have a time series-capable database or analytics engine wired up somewhere to deal with such state changes over time, and so, keeping that state in the graph has not been considered essential.

Conceptually it might be achieved by, e.g., adding a "values" or "observations" relationship to our sensor classes in addition to the existing lastKnownValue, where each such observation would have a start and end timestamp (which they get for free by virtue of being subclasses of Event). It would require a bit of thinking however, not least since these sensors are from Brick, where I believe they are not interested in such tracking to the same degree.

**Comment by hammar** [comment]
Closing this thread due to inactivity. Feel free to reopen if you'd like to continue discussion.
