### ISSUE TITLE
Add/integrate semantics for addressing southbound systems

### ISSUE THREAD

**Issue by hammar** [RealEstateCore/rec#66]
I.e., improve the quality of the tentatively designed BACNET, MODBUS, KNX, etc. classes, and also integrate w/ WoT Forms description and ideally other service descriptions also. We have data schemas defined in 3.2, now we need to express how to actually talk to the systems that use those schemas.

**Comment by JoelBender** [comment]
There is a proposal for BACnet in process in the Data Modeling Working Group (that is responsible for the CSML schema, an XML representation), so I'm watching this issue :-).  It won't be necessarily be describing MODBUS or KNX because those aren't specifically BACnet.  It also differs from your current MODBUS concepts (like there is a bacnet:Object class, but there is no rec:ModbusRegister).

**Comment by hammar** [comment]
Note after discussion w/ partners: one option is of course to not improve this part in REC itself, but rather to defer modeling of these concepts to other projects with deeper expertise and more maturity in this space, and to reuse (via cloning or linking) those projects' models. To be discussed at the next tech committee meeting in August.

**Comment by hammar** [comment]
Post REC4 we'll probably defer this to Brick Schema and/or ASHRAE initiatives. Closing for now, reopening if need arises.
