### ISSUE TITLE
Add "Campus" or "Complex" concept

### ISSUE THREAD

**Issue by hammar** [RealEstateCore/rec#81]
E.g., used for university or corporate campuses that may consist of several buildings or real estates, possibly distributed across a larger space (so not necessarily geographically contiguous).

Tentative design idea:

A "Campus" is a subclass of "Collection" that has as members only RealEstates.

**Comment by haris-zynka** [comment]
I'm not sure why but I guess Sweden differs in this aspect from others. [This page](https://en.wikipedia.org/wiki/Campus) states "A campus is traditionally the land on which a college or university and related institutional buildings are situated." and [this link](https://en.wikipedia.org/wiki/Campus_university) states "A campus university is a British term for a university situated on one site, ...". Same thing goes for Western Balkans. It's a piece of land where buildings belonging to that particular campus are aggregated in a relatively nearby distance. Basically you could put a piece of fence to surround all the era that belongs to one campus and it would be 1 shape and not 2 or more separate ones.

Campus should be quite close to Building Complex. On the same level but maybe not the same because I guess building complex must be linked together to be called complex while campus can have properties on it that don't belong to it.

I would love to hear more opinions on this one as this was quite problematic to represent in our system.

**Comment by hammar** [comment]
We're discussing the proper term to use for this. Candidate terms thrown around have been "Campus" and "Complex". My feeling is that we're gravitating towards the former, since the latter is much too generic and ambiguous, and since the former can have a broader interpretation (indeed, the wikipedia article linked above says "A modern campus is a collection of buildings and grounds that belong to a given institution, either academic or non-academic. Examples include the Googleplex and the Apple Campus."). Also, the use cases discussed thus far tend to focus on corporate or academic campuses. That said, if a better word can be found and if use cases can be given where the term "campus" is a non-starter, the floor is still very much open to debate.

**Comment by hammar** [comment]
Also, it is not given that Campus/Complex (or whatever term we end up with) should have only real estates as members. As pointed out in another discussion, our notion of real estate is actually as a legal term, not a geospatial entity (which is why we differentiate between "Land" and "RealEstate"). Concievably a large real estate could hold several pieces of disjoint land (in Swedish "skiften"), each of which could be part of different campuses, or contain different campuses.

Could it ever be said that a campus/complex contains or consists of something other than land and buildings? Could one say, e.g., that floors 2-4 of a certain building are part of an organizational campus, but not floors 5-6 of the same building (i.e., the floors are campus members)?

**Comment by haris-zynka** [comment]
> Also, it is not given that Campus/Complex (or whatever term we end up with) should have only real estates as members. As pointed out in another discussion, our notion of real estate is actually as a legal term, not a geospatial entity (which is why we differentiate between "Land" and "RealEstate"). Concievably a large real estate could hold several pieces of disjoint land (in Swedish "skiften"), each of which could be part of different campuses, or contain different campuses.
> 
> Could it ever be said that a campus/complex contains or consists of something other than land and buildings? Could one say, e.g., that floors 2-4 of a certain building are part of an organizational campus, but not floors 5-6 of the same building (i.e., the floors are campus members)?

I understand the points and I do agree that parts of campus / complex don't have to belong to same organisation, person, entity or whichever is the owner. However I was referring that I have seen cases (in our system) that 2 Real Estates in different parts of town (maybe even distance in km) have been assigned to same campus. They have no other connection than sole name of the campus connecting them because they belong to it. I find this quite useless in many ways but do understand that campuses besides being built out of pieces on land, that also may be partially divided so not all of it belongs to campus, can also be sold out partially, through time, leaving really weird campus if one may be called that. I was asking more in terms of "is this still valid expression for it" but I guess it is. If "owner" of the campus says so, it is then, and having any other connection is not necessary. 

That said I would say that campus cannot exist without at least 1 building, but I could be wrong. Important thing is to enable employees of such institutions to have close to 1:1 mapping or in other words to agree on good enough domain language.

Complex cannot be less than 2 structures. It's usually couple of them chained together but building complex is more than 1 structure linked together in some way. Those may even be 1 single real estate but there has to be more than 1 structure to call it a complex. Let's say we have apartment complex, it may look like 1 building but we will always see at least 2 entrances indicating that buildings are more like glued together rather than being the same one.

Why do I point these things out in manner to make them the same?

I thought that somehow we could have them on the same level.
1. Complexes will have separate measurements for each structure and so will campuses BUT
2. Often complexes will depend on same power, thermal, water, and other supplies
3. They will also have same backups
4. Campuses will have these things similar even tho campuses usually contain separate structures with a bit more space between them and not necessary same piece of land or Real Estate
5. They might as well have their own power generators or such which doesn't depend on external companies.

Having these discussions it's quite clear to me in the end that these cannot be on the same level so I'll need to split them in Zynka's system also.

**Comment by hammar** [comment]
Thanks for your input @haris-zynka, very insightful! We have previously discussed the topology or grouping of REC entities primarily as spatial (what is de facto there in the real world, and is held inside of what else, much like nested matryoshka dolls) or administrative (what do the laws and/or admin systems say about groupings of those aforementioned real world things). From your input it is clear that we also need to think about collections in terms of the underlying systems and their commonalities/overlaps/backups, etc. It is also clear that we will probably need to represent **both** campuses (disjoint buildings/lands but utilized by one institution or for one purpose) **and** complexes (interconnected buildings located in proximity to one another), and that these two concepts typically do not overlap much (other than of course that campuses can include building complexes).

**Comment by hammar** [comment]
We have the "Campus" definition included in the development branch at the moment, as a Collection of Location entities (quite generic). 

Complex, as we have seen, is more complex (pun not intended). It also relates to the spatial model (that is itself in need of updating). In some definitions, it seems building complexes always need to be interconnected physically/spatially, while in other definitions this is not a case. Since the updated (tentative) spatial model includes the notion of a Location as a contiguous spatial extent, it becomes important to figure out whether Complexes actually need to be contiguous or not.

Given the complexity in the notion of "Complex", I suggest that we punt this feature to a 3.4 release, so that we have time to think it through properly.

**Comment by hammar** [comment]
Closed in the Develop branch; "Campus" is a collection of spaces, and "Sub-building" is a part of a larger building complex (e.g., a tower, or a wing, or a free-standing sub-building connected to other building bodies using walkways or other means)
